FROM scratch
ARG GHOSIUM_VERSION
LABEL org.opencontainers.image.title="Ghosium Browser Windows Release Bundle"
LABEL org.opencontainers.image.description="Verified Windows x64 Ghosium Browser stable release artifacts"
LABEL org.opencontainers.image.source="https://github.com/bren-wp/Ghosium-Browser"
LABEL org.opencontainers.image.licenses="BSD-3-Clause"
LABEL org.opencontainers.image.version="${GHOSIUM_VERSION}"
COPY package/ /
